fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    registry:
      repo: 'git://github.com/puppetlabs/puppetlabs-registry.git'
      ref: '1.1.2'
  symlinks:
    w32time: "#{source_dir}"
